config/routes.rb
Rails.application.routes.draw do

  resources :all_city_program_data

  get 'set_language/english'

  get 'set_language/spanish'

  get 'set_language/polish'

  get ':controller/:action'
  get ':locale/:controller/:action'

  # post ':controller/:action'
  # post ':locale/:controller/:action'

  # twilio english 
  get("/twilio", { :controller => "send_text", :action => "send_text_message"})
  post('/', { :controller => 'twilio', :action => 'text'})
  post 'twilio/voice', defaults: { format: 'xml' }
   
  #static pages 
  root to: "pages#homepage"
  get('/our_story', { :controller => 'pages', :action => 'our_story' })
  get('/about_us', { :controller => 'pages', :action => 'about_us' })
  get('/how_mrelief_works', { :controller => 'pages', :action => 'how_mrelief_works' })
  get('/press_release', { :controller => 'pages', :action => 'press_release' })
  get('/public-template', { :controller => 'pages', :action => 'public_template' })
  get('/press_emails', { :controller => 'pages', :action => 'press_emails' })
  get('/chihacknight', { :controller => 'pages', :action => 'chihacknight' })
  get('/press_release/mrelief_espagnol', { :controller => 'pages', :action => 'mrelief_espagnol', as:  'mrelief_espagnol_press_release'})
  get('/press_release/students', { :controller => 'pages', :action => 'students', as: 'students_press_release'})
  get('/press_release/snap_transparency', { :controller => 'pages', :action => 'snap_transparency', as: 'snap_transparency_press_release' })
  get('/press_release/early_learning_finder', { :controller => 'pages', :action => 'early_learning_finder', as: 'early_learning_finder_press_release' })


  # all programs at once
  get("/filter", { :controller => "pages", :action => "filter" })
  get("/filtered_programs", { :controller => "pages", :action => "filtered_programs" })
  post("/community_resources", { :controller => "pages", :action => "community_resources" })

  get "early_learning_programs", to: "early_learning_programs#new", as: "early_learning"
  post "early_learning_programs_results", to: "early_learning_programs#create", as: "early_learning_programs_results"
  get "early_learning_more_results/:id", to: "early_learning_programs#more_results", as: "more_results"
  get "early_learning_privacy_policy", to: "early_learning_programs#early_learning_privacy_policy"
  get "educación_temprana", to: "early_learning_programs#set_spanish"

  # print
  get('/snap_eligibilities/print/:id', :controller => 'snap_eligibilities', :action => 'print')
  get('/ilsnap_spanish', :controller => 'snap_eligibilities', :action => 'set_spanish')

  # documents
  get("/snap_documents", { :controller => "snap_eligibilities", :action => "documents" })
  get("/rental_documents", { :controller => "rental_assistances", :action => "documents" })

  # clear session
  get("/session_clear", {:controller => "pages", :action => "session_clear"})

  # email list
  get 'email_lists/opt_in', to: 'email_lists#opt_in'
  get 'email_lists/confirm_email', to: 'email_lists#confirm_email'
  get 'email_lists/send_journalist_emails', to: 'email_lists#send_journalist_emails'

  resources :contact, only: [:index, :create]

  resources :wics

  resources :visions

  resources :snap_eligibility_seniors

  resources :snap_eligibilities

  resources :rta_free_rides

  resources :rental_assistances

  resources :programs

  resources :medicaids

  resources :housing_assistances

  resources :head_starts

  resources :family_nutritions

  resources :early_head_starts

  resources :dentals

  resources :child_care_vouchers

  resources :auto_repair_assistances

  resources :all_kids

  resources :all_city_programs

  resources :aabd_cashes

  resources :tanifs

  resources :service_centers

  resources :medicare_cost_sharings

  resources :organizations

  resources :laf_centers

  namespace :discovery do
    get 'programs', to: 'programs#index'
  end

  get "/cara", to: "organizations#cara"
  get "/alaskasnap", to: "organizations#alaskasnap"
  get "/catholic_charities", to: "organizations#catholic_charities"
end

app/models/aabd_cash.rb
class AabdCash < ActiveRecord::Base
end

app/models/all_kid.rb
class AllKid < ActiveRecord::Base
end

app/models/all_kids_data.rb
class AllKidsData < ActiveRecord::Base
end

app/models/dental.rb
class Dental < ActiveRecord::Base
end

app/models/email_list.rb
class EmailList < ActiveRecord::Base
end

app/models/feedback.rb
class Feedback

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :contact_first_name, :contact_last_name, :contact_email, :advertising_options, :feedback, :subject

  validates :contact_first_name, :contact_last_name, :contact_email, :advertising_options, :feedback, :presence => true
  validates :contact_email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true

  def initialize(hash)
    hash.each do |name, value|
      send("#{name}=", value)
    end
   end

  def persisted?
    false
  end

end

app/models/head_start.rb
class HeadStart < ActiveRecord::Base
end

app/models/laf_center.rb
class LafCenter < ActiveRecord::Base
end

app/models/medicaid.rb
class Medicaid < ActiveRecord::Base
end

app/models/medicaid_data.rb
class MedicaidData < ActiveRecord::Base
end

app/models/organization.rb
class Organization < ActiveRecord::Base
end

app/models/press_email.rb
class PressEmail < ActiveRecord::Base
end

app/models/program.rb
class Program < ActiveRecord::Base
  include R18n::Translated

  translations :name
  translations :description
end

app/models/tanf_data.rb
class TanfData < ActiveRecord::Base
end

app/models/tanif.rb
class Tanif < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/vision.rb
class Vision < ActiveRecord::Base
end

app/models/wic.rb
class Wic < ActiveRecord::Base
end

app/models/wic_data.rb
class WicData < ActiveRecord::Base
end

app/models/wic_location.rb
class WicLocation < ActiveRecord::Base
end

app/controllers/discovery/programs_controller.rb
class Discovery::ProgramsController < ApplicationController

	def index
		location = ["chicago", "illinois"]
		@programs = Program.where(location: location)
	end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:name, :category, :url, :description, :location)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/wics_helper.rb
module WicsHelper
end

app/views/programs/_calculator.es.html.haml
.row

/ calculator
.pull-left
  #js-calculator.calculator
    / Screen and clear key
    .cf.top
      %span.btn-calc.clear C
      .screen
    / operators and other keys
    .cf.keys
      %span.btn-calc 7
      %span.btn-calc 8
      %span.btn-calc 9
      %span.btn-calc.operator +
      %span.btn-calc 4
      %span.btn-calc 5
      %span.btn-calc 6
      %span.btn-calc.operator -
      %span.btn-calc 1
      %span.btn-calc 2
      %span.btn-calc 3
      %span.btn-calc.operator ÷
      %span.btn-calc 0
      %span.btn-calc .
      %span.btn-calc.eval =
      %span.btn-calc.operator x
/ close button

app/views/programs/_calculator.html.erb
<div class="col-md-3 sm-4 hidden-xs pull-left">
  <div class="calculator_box">
    <div class="row">
    <!-- calculator -->
    <div class="pull-left" style="padding-left:10px">
        <div id="js-calculator" class="calculator">

          <!-- Screen and clear key -->
          <div class="cf top">
            <span class="btn-calc clear">C</span>
            <div class="screen" id="screen-default"></div>
          </div>

          <!-- operators and other keys -->
          <div class="cf keys">
            <span class="btn-calc">7</span>
            <span class="btn-calc">8</span>
            <span class="btn-calc">9</span>
            <span class="btn-calc operator">+</span>
            <span class="btn-calc">4</span>
            <span class="btn-calc">5</span>
            <span class="btn-calc">6</span>
            <span class="btn-calc operator">-</span>
            <span class="btn-calc">1</span>
            <span class="btn-calc">2</span>
            <span class="btn-calc">3</span>
            <span class="btn-calc operator">÷</span>
            <span class="btn-calc">0</span>
            <span class="btn-calc">.</span>
            <span class="btn-calc eval">=</span>
            <span class="btn-calc operator">x</span>
          </div>

      </div>
    </div>

    </div>
  </div>
</div>


   

app/views/programs/_calculator_modal.html.erb
<a href="#" data-toggle="modal" data-target="#calculator" class="secondary-link" onclick="ga('send', 'event', 'button', 'early_learning', 'view_calculator', 1)">View Calculator</a>

<!-- All City Programs Modal -->
<div class="modal fade" id="calculator" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
          <button type="button" class="close close_modal" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">

            <div class="row">
            <div class="text-center">
            <p>Need help calculating your income? Use this calculator.</p>
            <div class="calculator-wrapper">
            <!-- calculator -->
            <div class="pull-left" style="padding-left:10px">
                <div id="js-calculator-popover" class="calculator">

                  <!-- Screen and clear key -->
                  <div class="cf top">
                    <span class="btn-calc clear">C</span>
                    <div class="screen" id="screen-popover"></div>
                  </div>

                  <!-- operators and other keys -->
                  <div class="cf keys">
                    <span class="btn-calc">7</span>
                    <span class="btn-calc">8</span>
                    <span class="btn-calc">9</span>
                    <span class="btn-calc operator">+</span>
                    <span class="btn-calc">4</span>
                    <span class="btn-calc">5</span>
                    <span class="btn-calc">6</span>
                    <span class="btn-calc operator">-</span>
                    <span class="btn-calc">1</span>
                    <span class="btn-calc">2</span>
                    <span class="btn-calc">3</span>
                    <span class="btn-calc operator">÷</span>
                    <span class="btn-calc">0</span>
                    <span class="btn-calc">.</span>
                    <span class="btn-calc eval">=</span>
                    <span class="btn-calc operator">x</span>
                  </div>

              </div>
            </div>
            </div>
            </div>
          </div>    
      </div>
    </div>
  </div>
</div>

app/views/programs/_dependent_question.html.erb
<div class="row">
  <div class="col-md-9 col-sm-10 col-xs-12">
    <label for="dependent_no">How many dependents (including yourself) are in your household?</label>
      <p type="button" data-toggle="popover" data-content="Number of people living in your household, including yourself, your spouse (if applicable), and/or resident for whom you (or you and your spouse) provided more than half of that person's  total financial support last year." data-placement="right" style="border: 0px; color: #4582ec;" class="popover-body">
      <input type="text" id="dependent_no" name="dependent_no" placeholder="For example: 3" class="form-field"  value ="<%= @current_user.try(:household_size) || @d.try(:dependent_no) %>" required>
      </p>
  </div>
</div>

app/views/programs/_disability_question.html.erb
   <div class="row">
     <div class="col-md-9 col-sm-10 col-xs-12">
       <label for="disabled" id="disabled">Does your household include a member who is receiving disability benefits?</label>
       <div class="radio-button">
       <% [ 'Yes, from Social Security', 'Yes, from the Railroad Retirement Board ', 'Yes, from Veterans Affairs', 'No' ].each do |disabled| %>
       <label for="disabled_<%= disabled %>" class="checkbox-question">
         <%= radio_button_tag 'disabled', disabled, @current_user.try(:disability_benefits) || @d.try(:disabled_status) == disabled, id: "disabled_#{disabled}" %>
         <%= disabled.humanize %> </label><br>
       <% end %>
       </div>
     </div>
   </div>

app/views/programs/_form.es.html.haml
= form_for(@program) do |f|
  - if @program.errors.any?
    #error_explanation
      %h2
        = pluralize(@program.errors.count, "error")
        prohibited this program from being saved:
      %ul
        - @program.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :category
    %br/
    = f.text_field :category
  .field
    = f.label :url
    %br/
    = f.text_field :url
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .field
    = f.label :location
    %br/
    = f.text_field :location
  .actions
    = f.submit

app/views/programs/_form.html.erb
<%= form_for(@program) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programs/_popover_calculator.html.erb
<div class="hidden-lg hidden-md hidden-sm">
<a href="#" data-toggle="modal" data-target="#calculator" class="secondary-link">View Calculator</a>
<!-- All City Programs Modal -->
<div class="modal fade" id="calculator" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close close_modal" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="text-center">
            <div class="calculator-wrapper">
            <!-- calculator -->
            <div class="pull-left" style="padding-left:10px">
              <div id="js-calculator-popover" class="calculator">
                <!-- Screen and clear key -->
                <div class="cf top">
                  <span class="btn-calc clear">C</span>
                  <div class="screen" id="screen-popover"></div>
                </div>
                <!-- operators and other keys -->
                <div class="cf keys">
                  <span class="btn-calc">7</span>
                  <span class="btn-calc">8</span>
                  <span class="btn-calc">9</span>
                  <span class="btn-calc operator">+</span>
                  <span class="btn-calc">4</span>
                  <span class="btn-calc">5</span>
                  <span class="btn-calc">6</span>
                  <span class="btn-calc operator">-</span>
                  <span class="btn-calc">1</span>
                  <span class="btn-calc">2</span>
                  <span class="btn-calc">3</span>
                  <span class="btn-calc operator">÷</span>
                  <span class="btn-calc">0</span>
                  <span class="btn-calc">.</span>
                  <span class="btn-calc eval">=</span>
                  <span class="btn-calc operator">x</span>
                </div>
              </div>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/programs/_zipcode_question.es.html.haml
.row
  .form-group.col-sm-9.pull-left
    %label{:for => "zipcode"}= t.zipcode_question.zipcode | "What is your zipcode?"
    %input#zipcode.form-control{:name => "zipcode", :placeholder => I18n.t('placeholder.example_zip', :default => "For example: 60615"), :required => "", :type => "text"}/

app/views/programs/edit.html.erb
<h1>Editing program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.es.html.haml
%div
  .row
    .col-md-10.col-md-offset-1
      %br/
      %br/
      %h1.page-header= t.programs.programs_for | "Programs for Chicago & Illinois"
      %p.subhead
        = t.programs.below_are | "Below are the benefits that mRelief currently offers for prescreening. Although these are not"

        %em= t.programs.all | "all"
        = t.programs.the_benefits | "the benefits the city and state offers, we are working to provide you with as much as we can."

%div
  %h4{:style => "text-align:center"}= t.programs.click_on | "Click on a benefit below to begin the pre-screening process."
%br/
/ City of Chicago Programs
.container
  .row
    .col-md-12
      %h3.program-heading{:style => "padding-bottom:0px"}= t.programs.chicago_programs | "CHICAGO PROGRAMS"
  %br/
  .row
    - chicago_programs = Program.where(:location => "chicago")
    - chicago_programs.where(:name_es => "Cupones de Alimentos").each_with_index do |program|
      .text-center
        %a.thumbnail{:href => program.url, :style => "padding:0 20px 20px 20px; width:350px; margin:auto"}
          %span.caption
            %h3= program.name
            %p= program.description
  %br/
  %hr/
  .row
    .col-md-12
      %h3.program-heading= t.programs.state_of | "EARLY CHILDHOOD PROGRAMS"
  %div
    .row
      - illinois_programs = Program.where(:location => "illinois")
      - illinois_programs.where(:name_es => "Búsqueda de Programas de Educación Temprana de Chicago").each_with_index do |program|
        .text-center
          %a.thumbnail{:href => program.url, :style => "padding:0 10px 10px 10px; width:350px; height:240px; margin:auto"}
            %span.caption
              %h3= program.name
              %p= program.description

app/views/programs/index.html.erb
<div class="container marquee">
  <div class ="row">
    <div class="col-md-10">
      <h2>All programs</h2>
      <p> Below are the benefits that mRelief currently offers for prescreening. Although these are not <em> all </em> the benefits the city and state offers, we are working to provide you with as much as we can. Click on a benefit below to begin the pre-screening process.</p>
    </div>
  </div>
</div>

<!-- City of Chicago Programs  -->
<div class="container program-wrapper">
 <div class="row">
    <div class="col-md-12 resources">
      <h3>City & State Programs Accessible in Chicago Community Service Centers</h3>
    </div>
  </div>

  <div class="row">
    <% chicago_programs = Program.where(:location => "chicago") %>
    <% chicago_programs.each_with_index do |program| %>

    <% if program.name_en == "All City Programs" %>
      <div class="col-md-4 programs">
        <h4><%= program.name %></h4>
        <p><%= program.description %></p>
        <a href="#" data-toggle="modal" data-target="#receiving_benefits">Continue &rarr;</a>
      </div>
    <% else %>
      <div class="col-md-4 programs" >
        <h4><%= program.name %></h4>
        <p><%= program.description %></p>
        <a href="<%= program.url %>" >Continue &rarr;</a>
      </div>
    <% end %>
  <% end %>
  </div>

<br>
  
<!--  Catholic Charities Programs  -->
  <div class="row">
    <div class="col-md-12 resources">
        <h3>Accessible in Catholic Charities</h3>
    </div>
  </div>

  <div class="row">
    <% chicago_programs = Program.where(:location => "catholic_charities") %>
    <% chicago_programs.each_with_index do |program| %>
  
      <div class="col-md-4 programs">
        <h4><%= program.name %></h4>
        <p><%= program.description %></p>
        <a href="<%= program.url %>">Continue &rarr;</a>
      </div>
    <% end %>
  </div>


<br>

<!-- Illinois Programs  -->
  <div class="row">
    <div class="col-md-12 resources">
        <!-- <h3>State of Illinois Programs</h3> -->
        <h3>Early Childhood Programs</h3>
    </div>
  </div>

  <div class="row">
    <% chicago_programs = Program.where(:location => "illinois") %>
    <% chicago_programs.each_with_index do |program| %>
  
      <div class="col-md-4 programs">
        <h4><%= program.name %></h4>
        <p><%= program.description %></p>
        <a href="<%= program.url %>">Continue &rarr;</a>
      </div>
    <% end %>
  </div>


    <div class="row">
      <div class="col-md-12 resources">
          <!-- <h3>State of Illinois Programs</h3> -->
          <h3>Employment Assistance Programs</h3>
      </div>
    </div>

    <div class="row">
      <% chicago_programs = Program.where(:location => "employment") %>
      <% chicago_programs.each_with_index do |program| %>
    
        <div class="col-md-4 programs">
          <h4><%= program.name %></h4>
          <p><%= program.description %></p>
          <a href="<%= program.url %>">Continue &rarr;</a>
        </div>
      <% end %>
    </div>

    <div class="row">
      <div class="col-md-12 resources">
          <!-- <h3>State of Illinois Programs</h3> -->
          <h3>Additional Programs</h3>
      </div>
    </div>

    <div class="row">
      <% chicago_programs = Program.where(:location => "general") %>
      <% chicago_programs.each_with_index do |program| %>
    
        <div class="col-md-4 programs">
          <h4><%= program.name %></h4>
          <p><%= program.description %></p>
          <a href="<%= program.url %>">Continue &rarr;</a>
        </div>
      <% end %>
    </div>
  </div>




<!-- All City Programs Modal -->
<div class="modal fade" id="receiving_benefits" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

       <div class="modal-header">
           <button type="button" class="close close_modal" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       </div>

        <div class="modal-body">
        <div class="container">
          <div class="col-md-9">
             <%= form_tag new_all_city_program_url, method: :get do %>

                <div class="benefits_checkboxes">
                <div class="row">
                  <p class="allthatapply">Check all of the benefits that you are currently receiving:</p>
                  <p class="col-sm-7 col-md-7">If you are already receiving a program and do NOT want to be screened for that program when checking your eligibility, please check all of the benefits that you are currently receiving. </p>
                 </div>

                 <%= hidden_field_tag :filtered_programs, "false" %>

                  <p>
                  <% if @current_user.try(:food_stamps) == "checked" %>
                    <%= check_box_tag "food_stamps", "checked", :checked => true %> Food Stamps<br>
                  <% else %>
                    <%= check_box_tag "food_stamps", "checked" %> Food Stamps<br>
                  <% end %>

                  <% if @current_user.try(:rta_ride_free) == "checked" %>
                    <%= check_box_tag "rta_ride_free", "checked", :checked => true %> RTA Ride Free<br>
                  <% else %>
                    <%= check_box_tag "rta_ride_free", "checked" %> RTA Ride Free<br>
                  <% end %>

                  <% if @current_user.try(:rental_assistance) == "checked" %>
                    <%= check_box_tag "rental_assistance", "checked", :checked => true %> Rental Assistance<br>
                  <% else %>
                    <%= check_box_tag "rental_assistance", "checked" %> Rental Assistance<br>
                  <% end %>

                  <% if @current_user.try(:all_kids) == "checked" %>
                    <%= check_box_tag "all_kids", "checked", :checked => true %> All Kids<br>
                  <% else %>
                    <%= check_box_tag "all_kids", "checked" %> All Kids<br>
                  <% end %>

                  <% if @current_user.try(:medicaid) == "checked" %>
                    <%= check_box_tag "medicaid", "checked", :checked => true %> Medicaid <br>
                  <% else %>
                    <%= check_box_tag "medicaid", "checked" %> Medicaid <br>
                  <% end %>

                  <% if @current_user.try(:medicare_cost_sharing) == "checked" %>
                    <%= check_box_tag "medicare_cost_sharing", "checked", :checked => true %> Medicare Cost Sharing<br>
                  <% else %>
                    <%= check_box_tag "medicare_cost_sharing", "checked" %> Medicare Cost Sharing<br>
                  <% end %>

                  <% if @current_user.try(:aabd) == "checked" %>
                    <%= check_box_tag "aabd", "checked", :checked => true %> AABD Cash Assistance<br>
                  <% else %>
                    <%= check_box_tag "aabd", "checked" %> AABD Cash Assistance<br>
                  <% end %>

                  <% if @current_user.try(:tanf) == "checked" %>
                    <%= check_box_tag "tanf", "checked", :checked => true %> TANF Cash Assistance<br>
                  <% else %>
                    <%= check_box_tag "tanf", "checked" %> TANF Cash Assistance<br>
                  <% end %>

                  <%= check_box_tag "none", "checked" %> None of the above<br>
                  </p>
                </div>

               <div class="form-group col-md-9">
                 <%= submit_tag "Enter", name: nil, :class => "btn btn-primary btn-sm col-sm-4", :style=>"display:block-inline;" %>
               </div>

              <% end %>

          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/programs/new.es.html.haml
%h1 New program
= render 'form'
= link_to 'Back', programs_path

app/views/programs/new.html.erb
<h1>New program</h1>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>