config/routes.rb
Rails.application.routes.draw do

  resources :all_city_program_data

  get 'set_language/english'

  get 'set_language/spanish'

  get 'set_language/polish'

  get ':controller/:action'
  get ':locale/:controller/:action'

  # post ':controller/:action'
  # post ':locale/:controller/:action'

  # twilio english 
  get("/twilio", { :controller => "send_text", :action => "send_text_message"})
  post('/', { :controller => 'twilio', :action => 'text'})
  post 'twilio/voice', defaults: { format: 'xml' }
   
  #static pages 
  root to: "pages#homepage"
  get('/our_story', { :controller => 'pages', :action => 'our_story' })
  get('/about_us', { :controller => 'pages', :action => 'about_us' })
  get('/how_mrelief_works', { :controller => 'pages', :action => 'how_mrelief_works' })
  get('/press_release', { :controller => 'pages', :action => 'press_release' })
  get('/public-template', { :controller => 'pages', :action => 'public_template' })
  get('/press_emails', { :controller => 'pages', :action => 'press_emails' })
  get('/chihacknight', { :controller => 'pages', :action => 'chihacknight' })
  get('/press_release/mrelief_espagnol', { :controller => 'pages', :action => 'mrelief_espagnol', as:  'mrelief_espagnol_press_release'})
  get('/press_release/students', { :controller => 'pages', :action => 'students', as: 'students_press_release'})
  get('/press_release/snap_transparency', { :controller => 'pages', :action => 'snap_transparency', as: 'snap_transparency_press_release' })
  get('/press_release/early_learning_finder', { :controller => 'pages', :action => 'early_learning_finder', as: 'early_learning_finder_press_release' })


  # all programs at once
  get("/filter", { :controller => "pages", :action => "filter" })
  get("/filtered_programs", { :controller => "pages", :action => "filtered_programs" })
  post("/community_resources", { :controller => "pages", :action => "community_resources" })

  get "early_learning_programs", to: "early_learning_programs#new", as: "early_learning"
  post "early_learning_programs_results", to: "early_learning_programs#create", as: "early_learning_programs_results"
  get "early_learning_more_results/:id", to: "early_learning_programs#more_results", as: "more_results"
  get "early_learning_privacy_policy", to: "early_learning_programs#early_learning_privacy_policy"
  get "educación_temprana", to: "early_learning_programs#set_spanish"

  # print
  get('/snap_eligibilities/print/:id', :controller => 'snap_eligibilities', :action => 'print')
  get('/ilsnap_spanish', :controller => 'snap_eligibilities', :action => 'set_spanish')

  # documents
  get("/snap_documents", { :controller => "snap_eligibilities", :action => "documents" })
  get("/rental_documents", { :controller => "rental_assistances", :action => "documents" })

  # clear session
  get("/session_clear", {:controller => "pages", :action => "session_clear"})

  # email list
  get 'email_lists/opt_in', to: 'email_lists#opt_in'
  get 'email_lists/confirm_email', to: 'email_lists#confirm_email'
  get 'email_lists/send_journalist_emails', to: 'email_lists#send_journalist_emails'

  resources :contact, only: [:index, :create]

  resources :wics

  resources :visions

  resources :snap_eligibility_seniors

  resources :snap_eligibilities

  resources :rta_free_rides

  resources :rental_assistances

  resources :programs

  resources :medicaids

  resources :housing_assistances

  resources :head_starts

  resources :family_nutritions

  resources :early_head_starts

  resources :dentals

  resources :child_care_vouchers

  resources :auto_repair_assistances

  resources :all_kids

  resources :all_city_programs

  resources :aabd_cashes

  resources :tanifs

  resources :service_centers

  resources :medicare_cost_sharings

  resources :organizations

  resources :laf_centers

  namespace :discovery do
    get 'programs', to: 'programs#index'
  end

  get "/cara", to: "organizations#cara"
  get "/alaskasnap", to: "organizations#alaskasnap"
  get "/catholic_charities", to: "organizations#catholic_charities"
end

app/models/rental_assistance.rb
class RentalAssistance < ActiveRecord::Base
end

app/controllers/rental_assistances_controller.rb
class RentalAssistancesController < ApplicationController
  require 'numbers_in_words'
  require 'numbers_in_words/duck_punch' #see why later
  before_action :set_rental_assistance, only: [:show, :edit, :update, :destroy]

  skip_before_action :authenticate_user!, :only => :index
  skip_before_filter :verify_authenticity_token

  def new
    @rental_assistance = RentalAssistance.new

    if params[:data].present? 
      @d = RentalAssistanceData.new(JSON.parse(params[:data])) 
    else 
      @d = RentalAssistanceData.new
    end
    
    @current_user = current_user
  end

  def create
    @d = RentalAssistanceData.new
    if params[:rental_dependent_no] !~ /\D/  # returns true if all numbers
      rental_dependent_no = params[:dependent_no].to_i
      @d.dependent_no = rental_dependent_no
    else
      rental_dependent_no = params[:dependent_no].in_numbers
      @d.dependent_no = rental_dependent_no
    end

    rental_gross_income = params[:rental_gross_income]
    rental_gross_income = rental_gross_income.gsub(/[^0-9\.]/, '').to_i
    if rental_gross_income !~ /\D/
      rental_gross_income = rental_gross_income.to_i
      @d.ninety_day_gross_income = rental_gross_income
    else
      if rental_gross_income.include?("dollars")
        rental_gross_income.slice!"dollars"
      end
      rental_gross_income = rental_gross_income.in_numbers
      @d.ninety_day_gross_income = rental_gross_income
    end

    if rental_gross_income.present? && rental_dependent_no.present?
      rental_eligibility = RentalAssistance.find_by({ :rental_dependent_no => rental_dependent_no })
      rental_cut_off =  rental_eligibility.rental_gross_income
      rental_cut_off_plus_200 = rental_eligibility.rental_gross_income + 200

       p "rental_gross_income = #{rental_gross_income}"
       p "rental_eligibility.rental_gross_income = #{rental_eligibility.rental_gross_income}"

       if params[:lease] == "no" || params[:next_rent] == "no"
         @eligible = "no"
         @d.rental_eligibility_status = @eligible
       elsif params[:lease] == "yes"
        if rental_gross_income < rental_eligibility.rental_gross_income && params[:rental_status] != "none of the above"
          @eligible = "yes"
          @d.rental_eligibility_status = @eligible
        elsif rental_gross_income< rental_cut_off_plus_200 && rental_gross_income >= rental_cut_off && params[:rental_status] != "none of the above"
          @eligible = "maybe"
          @d.rental_eligibility_status = @eligible
        else
          @eligible = "no"
          @d.rental_eligibility_status = @eligible
         end
        end # closes the if statement about the lease agreement
      end #closes first if statement

      # RENTAL STATUS VARIABLE
      @rental_status = ""
      if params[:medical].present?
        @medical_circumstance = "yes"
        @rental_status = @rental_status + "medical circumstance, " 
      end
      if params[:natural_disaster].present?
        @natural_disaster = "yes"
        @rental_status = @rental_status + "a victim of natural disaster or fire, "
      end
      if params[:eviction].present?
        @eviction = "yes"
        @rental_status = @rental_status + "a recipient of an eviction notice, "
      end
      if params[:income].present?
        @temporary_loss = "yes"
        @rental_status = @rental_status + "have experienced a temporary loss of income, "

      end
      if params[:domestic_violence] == "a victim of domestic violence"
        @domestic_violence = "yes"
        @rental_status =  @rental_status + "a victim of domestic violence, "
      end

      # DATA STORAGE
      @d.user_location = params[:user_location]
      @d.phone_number = params[:phone_number] if params[:phone_number].present?
      @d.name_on_lease = params[:lease]
      @d.next_month_rent = params[:next_rent]
      @d.rental_status = @rental_status
      @d.zipcode = params[:zipcode].chomp(".0")
      @d.save

      @d_json = @d.attributes.to_json


      # RESOURCE LOOKUP
      @user_zipcode = params[:zipcode]
      @zipcode = @user_zipcode << ".0"
      @lafcenter = LafCenter.find_by(:zipcode => @zipcode)
      puts "#{@lafcenter}"

      if @lafcenter.present?
      else
        @lafcenter = LafCenter.find_by(:center => "King Community Service Center")
        @laf_disclaimer = "We do not have an estimation of the nearest center that is in range for you at this time. But we recommend going to the center below."
      end

      housing = []
      ServiceCenter.all.each do |center|
        if center.description.match("housing")
          housing.push(center)
        end
      end

        @pb_zipcode = @user_zipcode.chomp(".0")
        @resources = housing
        @resources_zip = []

        housing.each do |center|
          if center.zip.match(@pb_zipcode)
            @resources_zip.push(center)
          end
        end

        #in this case there are 2 housing centers in the user's zip
        if @resources_zip.count >= 2
           @resources = @resources_zip
        end
        #in this case there is 1 aabd center in the user's zip
        if @resources_zip.count == 1
           @resources_first = @resources_zip.first
           @resources_second = @resources.first
        end
        #in this caser there are no aabd centers in the user's zip
        if  @resources_zip.count == 0
            @resources_first = @resources.first
            @resources_second = @resources.second
        end

      if params[:lease].present? && params[:next_rent].present?
        if params[:medical].present? || params[:natural_disaster].present? || params[:eviction].present? || params[:income].present? || params[:domestic_violence].present? || params[:rental_status].present?
        else
           flash.now[:alert] = 'Looks like you forgot to answer a question! Please answer all questions below.'
          render "new"
        end
      else
         flash.now[:alert] = 'Looks like you forgot to answer a question! Please answer all questions below.'
        render "new"
      end

    end #closes method

  def documents

    @medical_circumstance = params[:medical_circumstance] 
    @natural_disaster = params[:natural_disaster]
    @temporary_loss = params[:temporary_loss]
    @domestic_violence = params[:domestic_violence]
    @eviction = params[:eviction]

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental_assistance
      @rental_assistance = RentalAssistance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_assistance_params
      params.require(:rental_assistance).permit(:rental_dependent_no, :rental_gross_income, :rental_status)
    end
end

app/helpers/rental_assistances_helper.rb
module RentalAssistancesHelper
end

app/views/rental_assistances/_documents.html.erb
    <ul class="list-group" style="text-align:left;">

       <% if @medical_circumstance == "yes" %>
       <li class="list-group-item">Documentation of Emergency - Medical Circumstance<br>
       You must be able to obtain documents from your employer showing that you took time off as well as from the hospital or attending physician.
       </li>
       <% end %>

       <% if @natural_disaster == "yes" %>
       <li class="list-group-item">Documentation of Emergency - Natural Disaster <br>
       You must be able to prove this by obtaining documents from a fire marshall (standard fire department reports). For floods, please provide a letter from your landlord and photographs.
       </li>
       <% end %>

       <% if @eviction == "yes" %>
       <li class="list-group-item">Documentation of Emergency - Eviction Notice
       </li>
       <% end %>

      <% if @temporary_loss == "yes"%>
      <li class="list-group-item">Documentation of Emergency - Temporary Loss of Income<br>
      You must provide last 90 days of pay stubs and a letter from employer stating (layoff, termination, etc) and the return date to work. You can also provide unemployment assistance documentation.
      </li>
      <% end %>

      <% if @domestic_violence == "yes" %>
      <li class="list-group-item">Documentation of Emergency - Domestic Violence<!-- <br>
      You must be able to prove this by providing a report from the police department or a document showing an order of protection/restraining order. -->
      </li>
      <% end %>

      <li class="list-group-item">Notarized 5 day notice</li>
      <li class="list-group-item">90 days of income documetation</li>
      <li class="list-group-item">State I.D. / Driver's Lincense (everyone 18 and older)</li>
      <li class="list-group-item">Social Security Card (all household members)</li>
      <li class="list-group-item">Current Lease</li>
      <li class="list-group-item">3 rent receipts</li>
      <li class="list-group-item">Property Owner / Management Company Agreement</li>
      <li class="list-group-item">Property tax bill</li>
      <li class="list-group-item">W9</li>
      <li class="list-group-item">Property manager affidavit (if applicable)</li>
      <li class="list-group-item">Payment plan (if applicable) </li>
    </ul>
    

app/views/rental_assistances/_form.es.html.haml
= form_for(@rental_assistance) do |f|
  - if @rental_assistance.errors.any?
    #error_explanation
      %h2
        = pluralize(@rental_assistance.errors.count, "error")
        prohibited this rental_assistance from being saved:
      %ul
        - @rental_assistance.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :rental_dependent_no
    %br/
    = f.number_field :rental_dependent_no
  .field
    = f.label :rental_gross_income
    %br/
    = f.text_field :rental_gross_income
  .field
    = f.label :rental_status
    %br/
    = f.number_field :rental_status
  .actions
    = f.submit

app/views/rental_assistances/_form.html.erb
<%= form_for(@rental_assistance) do |f| %>
  <% if @rental_assistance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rental_assistance.errors.count, "error") %> prohibited this rental_assistance from being saved:</h2>

      <ul>
      <% @rental_assistance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rental_dependent_no %><br>
    <%= f.number_field :rental_dependent_no %>
  </div>
  <div class="field">
    <%= f.label :rental_gross_income %><br>
    <%= f.text_field :rental_gross_income %>
  </div>
  <div class="field">
    <%= f.label :rental_status %><br>
    <%= f.number_field :rental_status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rental_assistances/create.es.html.haml
- if @eligible == "yes"
  .page-header
  .row{:style => "text-align:center;"}
    .col-md-8.col-md-offset-2
      %i.fa.fa-check-circle.fa-5x
      %h1 You may be in luck!
      %h4 Based on your rental status, household size and income, you likely qualify for rental assistance.  Applications can be filed at any of the City’s six Community Service Centers.
      - if @medical_circumstance == "yes"
        %h4 You must be able to obtain documents from your employer showing that you took time off as well as from the hospital or attending physician.
      - elsif @natural_disaster == "yes"
        %h4
          You must be able to prove this by obtaining documents from a fire marshall (standard fire department reports). For floods, please provide a letter from your landlord and photographs.
      - elsif @temporary_loss == "yes"
        %h4 You must provide last 90 days of pay stubs and a letter from employer stating (layoff, termination, etc) and the return date to work. You can also provide unemployment assistance documentation.
      - elsif @domestic_violence == "yes"
        %h4 You must be able to prove this by providing a report from the police department or a document showing an order of protection/restraining order.
      %h4 The final decision will be made one-on-one by the case manager.
      %br/
      %br/
      .row
        .text-center
          - if @laf_disclaimer.present?
            %p.subhead= @laf_disclaimer
          - else
            %p.subhead Based on your zipcode, here is the nearest Community Service Center to complete your application:
          .col-md-offset-3.col-md-6.col-sm-6.text-center{:style => "text-align:center;"}
            %ul.list-group{:style => "text-align:left;"}
              %li.list-group-item{:style => "font-weight:bold"}
                = @lafcenter.center
              %li.list-group-item
                %i.fa.fa-map-marker
                = @lafcenter.address
                = @lafcenter.city
                , #{@lafcenter.zipcode.to_i}
              %li.list-group-item
                %i.fa.fa-phone
                = @lafcenter.telephone
              %li.list-group-item
                Days that Spanish is spoken - #{@lafcenter.spanish}
            %br/
            %br/
      .row
        %p.subhead or call 3-1-1.
- elsif @eligible == "maybe"
  %br/
  %br/
  .row{:style => "text-align:center;"}
    .col-md-8.col-md-offset-2
      %i.fa.fa-exclamation-circle.fa-5x
      %h1 Close enough to apply!
      %h4 According to the income guidelines of Rental Assistance, you make too much money to apply. However, in some cases the city may make an exception. Applications can be filed at any of the City’s six Community Service Centers.
      %br/
      .row
        .text-center
          - if @laf_disclaimer.present?
            %p.subhead= @laf_disclaimer
          - else
            %p.subhead Based on your zipcode, here is the nearest Community Service Center to complete your application:
          .col-md-offset-3.col-md-6.col-sm-6.text-center{:style => "text-align:center;"}
            %ul.list-group{:style => "text-align:left;"}
              %li.list-group-item{:style => "font-weight:bold"}
                = @lafcenter.center
              %li.list-group-item
                %i.fa.fa-map-marker
                = @lafcenter.address
                = @lafcenter.city
                , #{@lafcenter.zipcode.to_i}
              %li.list-group-item
                %i.fa.fa-phone
                = @lafcenter.telephone
              %li.list-group-item
                Days that Spanish is spoken - #{@lafcenter.spanish}
            %br/
            %br/
      .row
        %p.subhead or call 3-1-1.
- elsif @eligible == "no"
  .page-header
  .row{:style => "text-align:center;"}
    .col-md-8.col-md-offset-2
      %h1 Something else in mind!
      %h4 Based on your household size and income, you likely do not qualify for Rental Assistance.
      %br/
      .row
        %h4 Here are some additional resources from Purple Binder:
      %br/
      .row
        - if @housing_resources_zip.count >= 2
          .col-md-6.col-sm-6
            %ul.list-group{:style => "text-align:left;"}
              %li.list-group-item{:style => "font-weight:bold"}
                = @housing_resources_zip.first.name
              %li.list-group-item
                %i.fa.fa-map-marker
                = @housing_resources_zip.first.street
                = @housing_resources_zip.first.city
                = @housing_resources_zip.first.state
                , #{@housing_resources_zip.first.zip}
              %li.list-group-item
                %i.fa.fa-phone
                = @housing_resources_zip.first.phone
          .col-md-6.col-sm-6
            %ul.list-group{:style => "text-align:left;"}
              %li.list-group-item{:style => "font-weight:bold"}
                = @housing_resources_zip.second.name
              %li.list-group-item
                %i.fa.fa-map-marker
                = @housing_resources_zip.second.street
                = @housing_resources_zip.second.city
                = @housing_resources_zip.second.state
                , #{@housing_resources_zip.second.zip}
              %li.list-group-item
                %i.fa.fa-phone
                = @housing_resources_zip.second.phone
      .row
        - if @housing_resources_first.present?
          .col-md-6.col-sm-6
            %ul.list-group{:style => "text-align:left;"}
              %li.list-group-item{:style => "font-weight:bold"}
                = @housing_resources_first.name
              %li.list-group-item
                %i.fa.fa-map-marker
                = @housing_resources_first.street
                = @housing_resources_first.city
                = @housing_resources_first.state
                , #{@housing_resources_first.zip}
              %li.list-group-item
                %i.fa.fa-phone
                = @housing_resources_first.phone
          .col-md-6.col-sm-6
            %ul.list-group{:style => "text-align:left;"}
              %li.list-group-item{:style => "font-weight:bold"}
                = @housing_resources_second.name
              %li.list-group-item
                %i.fa.fa-map-marker
                = @housing_resources_second.street
                = @housing_resources_second.city
                = @housing_resources_second.state
                , #{@housing_resources_second.zip}
              %li.list-group-item
                %i.fa.fa-phone
                = @housing_resources_second.phone
      = image_tag("pblogo.jpg", :class => "logo-padding")

app/views/rental_assistances/create.html.erb
<div class="container marquee">
<%= render "layouts/print_button" %>
 <% if @eligible == "yes" %>

       <div class="row" >
          <div class="col-md-7">
            <h1>You may be in luck!</h1>
              <p> Based on your rental status, household size and income, you likely qualify for rental assistance.  Applications can be filed at any of the City’s six Community Service Centers.</p>

              <% if @medical_circumstance == "yes" %>
                <p>You must be able to obtain documents from your employer showing that you took time off as well as from the hospital or attending physician.</p>
              <% end %>

              <% if @natural_disaster == "yes" %>
                <p>You must be able to prove this by obtaining documents from a fire marshall (standard fire department reports). For floods, please provide a letter from your landlord and photographs.
                </p>
              <% end %>

              <% if @temporary_loss == "yes"%>
                <p>You must provide last 90 days of pay stubs and a letter from employer stating (layoff, termination, etc) and the return date to work. You can also provide unemployment assistance documentation.</p>
              <% end %>

              <% if @domestic_violence == "yes"%>
                <p>You must be able to prove this by providing a report from the police department or a document showing an order of protection/restraining order.</p>

              <% end %>

              <p>The final decision will be made one-on-one by the case manager.</p>


        <section class="content-section resources">
          <h3>Resources</h3>
            <% if @laf_disclaimer.present? %>
          <p><%= @laf_disclaimer %></p>
          <% else  %>
          <p> Based on your zipcode, here is the nearest Community Service Center to complete your application:  </p>
          <% end %>
        <%= render 'layouts/community_center' %>
          <p>or call 3-1-1.</p>
       </section>

      <section class="content-section resources">
        <h3>Documents You Need to Apply</h3>
        <%= render "rental_assistances/documents" %>
        </section>

       </div>
     </div>

 <% elsif @eligible == "maybe" %>

   <div class="row" >
     <div class="col-md-7">
        <h1>Close enough to apply!</h1>
        <p>According to the income guidelines of Rental Assistance, you make too much money to apply. However, in some cases the

        <section class="content-section resources">
         <h3>Resources</h3>
         <% if @laf_disclaimer.present? %>
           <p><%= @laf_disclaimer %></p>
         <% else  %>
           <p> Based on your zipcode, here is the nearest Community Service Center to complete your application:  </p>
        <% end %>
         <%= render 'layouts/community_center' %>
          <p>or call 3-1-1.</p>
        </section>

    </div>
  </div>

<% elsif @eligible == "no" %>

    <div class="row">
      <div class="col-md-7">
        <h1>Results: Something else in mind!</h1>
        <p>Based on your household size and income, you likely do not qualify for Rental Assistance.</p>
        <%= render "layouts/purple_binder_resources" %>
      </div>
    </div>

  <% end %>
</div>

<%= render "layouts/conversion_tracking" %>

app/views/rental_assistances/documents.html.erb
<div class="container marquee">
<section class="content-section">
  <div class="row">
    <div class="col-md-12">
      <h1>Required Documents for Rental Assistance</h1>
      <div class="col-md-6">
        <%= render "rental_assistances/documents" %>
      </div>
    </div>
  </div>
</section>
</div>

app/views/rental_assistances/edit.es.html.haml
%h1 Editing rental_assistance
= render 'form'
= link_to 'Show', @rental_assistance
|
\#{link_to 'Back', rental_assistances_path}

app/views/rental_assistances/edit.html.erb
<h1>Editing rental_assistance</h1>

<%= render 'form' %>

<%= link_to 'Show', @rental_assistance %> |
<%= link_to 'Back', rental_assistances_path %>

app/views/rental_assistances/index.es.html.haml
%h1 Listing rental_assistances
%table
  %thead
    %tr
      %th Rental dependent no
      %th Rental gross income
      %th Rental status
      %th{:colspan => "3"}
  %tbody
    - @rental_assistances.each do |rental_assistance|
      %tr
        %td= rental_assistance.rental_dependent_no
        %td= rental_assistance.rental_gross_income
        %td= rental_assistance.rental_status
        %td= link_to 'Show', rental_assistance
        %td= link_to 'Edit', edit_rental_assistance_path(rental_assistance)
        %td= link_to 'Destroy', rental_assistance, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Rental assistance', new_rental_assistance_path

app/views/rental_assistances/index.html.erb
<h1>Listing rental_assistances</h1>

<table>
  <thead>
    <tr>
      <th>Rental dependent no</th>
      <th>Rental gross income</th>
      <th>Rental status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rental_assistances.each do |rental_assistance| %>
      <tr>
        <td><%= rental_assistance.rental_dependent_no %></td>
        <td><%= rental_assistance.rental_gross_income %></td>
        <td><%= rental_assistance.rental_status %></td>
        <td><%= link_to 'Show', rental_assistance %></td>
        <td><%= link_to 'Edit', edit_rental_assistance_path(rental_assistance) %></td>
        <td><%= link_to 'Destroy', rental_assistance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rental assistance', new_rental_assistance_path %>

app/views/rental_assistances/show.es.html.haml
%p#notice= notice
%p
  %strong Rental dependent no:
  = @rental_assistance.rental_dependent_no
%p
  %strong Rental gross income:
  = @rental_assistance.rental_gross_income
%p
  %strong Rental status:
  = @rental_assistance.rental_status
= link_to 'Edit', edit_rental_assistance_path(@rental_assistance)
|
\#{link_to 'Back', rental_assistances_path}

app/views/rental_assistances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rental dependent no:</strong>
  <%= @rental_assistance.rental_dependent_no %>
</p>

<p>
  <strong>Rental gross income:</strong>
  <%= @rental_assistance.rental_gross_income %>
</p>

<p>
  <strong>Rental status:</strong>
  <%= @rental_assistance.rental_status %>
</p>

<%= link_to 'Edit', edit_rental_assistance_path(@rental_assistance) %> |
<%= link_to 'Back', rental_assistances_path %>