config/routes.rb
Rails.application.routes.draw do

  resources :all_city_program_data

  get 'set_language/english'

  get 'set_language/spanish'

  get 'set_language/polish'

  get ':controller/:action'
  get ':locale/:controller/:action'

  # post ':controller/:action'
  # post ':locale/:controller/:action'

  # twilio english 
  get("/twilio", { :controller => "send_text", :action => "send_text_message"})
  post('/', { :controller => 'twilio', :action => 'text'})
  post 'twilio/voice', defaults: { format: 'xml' }
   
  #static pages 
  root to: "pages#homepage"
  get('/our_story', { :controller => 'pages', :action => 'our_story' })
  get('/about_us', { :controller => 'pages', :action => 'about_us' })
  get('/how_mrelief_works', { :controller => 'pages', :action => 'how_mrelief_works' })
  get('/press_release', { :controller => 'pages', :action => 'press_release' })
  get('/public-template', { :controller => 'pages', :action => 'public_template' })
  get('/press_emails', { :controller => 'pages', :action => 'press_emails' })
  get('/chihacknight', { :controller => 'pages', :action => 'chihacknight' })
  get('/press_release/mrelief_espagnol', { :controller => 'pages', :action => 'mrelief_espagnol', as:  'mrelief_espagnol_press_release'})
  get('/press_release/students', { :controller => 'pages', :action => 'students', as: 'students_press_release'})
  get('/press_release/snap_transparency', { :controller => 'pages', :action => 'snap_transparency', as: 'snap_transparency_press_release' })
  get('/press_release/early_learning_finder', { :controller => 'pages', :action => 'early_learning_finder', as: 'early_learning_finder_press_release' })


  # all programs at once
  get("/filter", { :controller => "pages", :action => "filter" })
  get("/filtered_programs", { :controller => "pages", :action => "filtered_programs" })
  post("/community_resources", { :controller => "pages", :action => "community_resources" })

  get "early_learning_programs", to: "early_learning_programs#new", as: "early_learning"
  post "early_learning_programs_results", to: "early_learning_programs#create", as: "early_learning_programs_results"
  get "early_learning_more_results/:id", to: "early_learning_programs#more_results", as: "more_results"
  get "early_learning_privacy_policy", to: "early_learning_programs#early_learning_privacy_policy"
  get "educación_temprana", to: "early_learning_programs#set_spanish"

  # print
  get('/snap_eligibilities/print/:id', :controller => 'snap_eligibilities', :action => 'print')
  get('/ilsnap_spanish', :controller => 'snap_eligibilities', :action => 'set_spanish')

  # documents
  get("/snap_documents", { :controller => "snap_eligibilities", :action => "documents" })
  get("/rental_documents", { :controller => "rental_assistances", :action => "documents" })

  # clear session
  get("/session_clear", {:controller => "pages", :action => "session_clear"})

  # email list
  get 'email_lists/opt_in', to: 'email_lists#opt_in'
  get 'email_lists/confirm_email', to: 'email_lists#confirm_email'
  get 'email_lists/send_journalist_emails', to: 'email_lists#send_journalist_emails'

  resources :contact, only: [:index, :create]

  resources :wics

  resources :visions

  resources :snap_eligibility_seniors

  resources :snap_eligibilities

  resources :rta_free_rides

  resources :rental_assistances

  resources :programs

  resources :medicaids

  resources :housing_assistances

  resources :head_starts

  resources :family_nutritions

  resources :early_head_starts

  resources :dentals

  resources :child_care_vouchers

  resources :auto_repair_assistances

  resources :all_kids

  resources :all_city_programs

  resources :aabd_cashes

  resources :tanifs

  resources :service_centers

  resources :medicare_cost_sharings

  resources :organizations

  resources :laf_centers

  namespace :discovery do
    get 'programs', to: 'programs#index'
  end

  get "/cara", to: "organizations#cara"
  get "/alaskasnap", to: "organizations#alaskasnap"
  get "/catholic_charities", to: "organizations#catholic_charities"
end

app/models/aabd_cash.rb
class AabdCash < ActiveRecord::Base
end

app/models/all_kid.rb
class AllKid < ActiveRecord::Base
end

app/models/all_kids_data.rb
class AllKidsData < ActiveRecord::Base
end

app/models/dental.rb
class Dental < ActiveRecord::Base
end

app/models/email_list.rb
class EmailList < ActiveRecord::Base
end

app/models/feedback.rb
class Feedback

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :contact_first_name, :contact_last_name, :contact_email, :advertising_options, :feedback, :subject

  validates :contact_first_name, :contact_last_name, :contact_email, :advertising_options, :feedback, :presence => true
  validates :contact_email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true

  def initialize(hash)
    hash.each do |name, value|
      send("#{name}=", value)
    end
   end

  def persisted?
    false
  end

end

app/models/head_start.rb
class HeadStart < ActiveRecord::Base
end

app/models/laf_center.rb
class LafCenter < ActiveRecord::Base
end

app/models/medicaid.rb
class Medicaid < ActiveRecord::Base
end

app/models/organization.rb
class Organization < ActiveRecord::Base
end

app/models/press_email.rb
class PressEmail < ActiveRecord::Base
end

app/models/program.rb
class Program < ActiveRecord::Base
  include R18n::Translated

  translations :name
  translations :description
end

app/models/tanf_data.rb
class TanfData < ActiveRecord::Base
end

app/models/tanif.rb
class Tanif < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/vision.rb
class Vision < ActiveRecord::Base
end

app/models/wic.rb
class Wic < ActiveRecord::Base
end

app/models/wic_data.rb
class WicData < ActiveRecord::Base
end

app/models/wic_location.rb
class WicLocation < ActiveRecord::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def index


  end

  def create

    @contact_first_name = params[:contact_first_name]
    @contact_last_name = params[:contact_last_name]
    @contact_email = params[:contact_email]
    @advertising_options = params[:advertising_options]
    @request = params[:request]
    @feedback = params[:feedback]


    if @feedback.present?
      NotificationsMailer.send_simple_message(@contact_first_name, @contact_last_name, @contact_email,
        @advertising_options, @request, @feedback).deliver
      NotificationsMailer.send_simple_message_to_rose(@contact_first_name, @contact_last_name, @contact_email,
        @advertising_options, @request, @feedback).deliver
      redirect_to :back, :notice => "Feedback was successfully sent. Thank you!"
    else
      flash.now.alert = "Please fill all fields."
      render :index
    end


  end



end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/wics_helper.rb
module WicsHelper
end

app/views/contact/index.es.html.haml
.container
  .row
    .page-header
    = notice
    = alert
    .col-md-8.col-md-offset-2
      %h3.text-center= t.contact_us.we_would | "We would love to hear from you!"
      %br/
      = form_tag(contact_index_url) do
        .form-group
          = label_tag(:contact_first_name, I18n.t('contact_us.first_name', :default => "First Name"))
          = text_field_tag(:contact_first_name, nil, {:class => "form-control"})
        .form-group
          /
            <label for="contact_last_name">Last Name</label>
            <input type="text" class="form-control" style="max-width:350px" id="contact_last_name">
          = label_tag(:contact_last_name, I18n.t('contact_us.last_name', :default => "Last Name"))
          = text_field_tag(:contact_last_name, nil, {:class => "form-control"})
        .form-group
          /
            <label for="contact_email">Email</label>
            <input type="email" class="form-control" style="max-width:350px" id="contact_email">
          = label_tag(:contact_email, I18n.t('contact_us.email', :default => "Email"))
          = email_field_tag(:contact_email, nil, {:class => "form-control"})
        .form-group
          = label_tag(:advertising_title, I18n.t('contact_us.how_did', :default => "How did you hear about us?"))
          = select_tag(:advertising_options, options_for_select([[I18n.t('contact_us.none', :default => 'None'), 'None'], [I18n.t('contact_us.ads', :default => 'Advertisements'), 'Advertisements'], [I18n.t('contact_us.events', :default => 'At an event'), 'At an Event'], [I18n.t('contact_us.community', :default => 'Community service center'), 'Community Service Center'], [I18n.t('contact_us.someone_else', :default => 'From someone else'), 'From Someone Else'], [I18n.t('contact_us.internet_search', :default => 'Internet search'), 'Internet Search'], [I18n.t('contact_us.social_media', :default => 'Social media'), 'Social Media'], [I18n.t('contact_us.other', :default => 'Other'), 'Other']]), {:class => "form-control"})
        .form-group
          = label_tag(:request, I18n.t('contact_us.request', :default => "What is your request related to?"))
          = select_tag(:request, options_for_select([[I18n.t('contact_us.press', :default => 'Press'), 'Press'], [I18n.t('contact_us.grants', :default => 'Grants/Investment '), 'Grants/Investment '], [I18n.t('contact_us.feedback'), 'Feedback About the Site'], [I18n.t('contact_us.bug_or_problem', :default => 'A Bug or Problem you Had'), 'A Bug or Problem you Had'], [I18n.t('contact_us.something_else', :default => 'Something else'), 'Something Else']]), {:class => "form-control"})
        .form-group
          = label_tag(:feedback, I18n.t('contact_us.message', :default => "Your message"))
          = text_area_tag(:feedback, nil, {:class => "form-control", :rows => "5"})
        %div
          = submit_tag(I18n.t('contact_us.submit', :default => "Submit"), :class => "btn btn-primary")
  .divider
  %br/
  %br/
  %div
    %p.subhead Some ways to get in touch with us
  %div{:style => "padding-bottom:100px; text-align:center"}
    %a{:href => "mailto:mrelief.form@gmail.com"}
      %i.fa.fa-envelope-square{:style => "  margin:30px; font-size:72px"}
    %a{:href => "https://plus.google.com/117049110248209318421 "}
      %i.fa.fa-google-plus-square{:style => "  margin:30px; font-size:72px"}
    %a{:href => "https://twitter.com/mrelief_form"}
      %i.fa.fa-twitter-square{:style => "margin:30px;   font-size:72px"}
    %a{:href => "https://www.facebook.com/mRelief"}
      %i.fa.fa-facebook-square{:style => "  margin:30px; font-size:72px"}

app/views/contact/index.html.erb
<div class="container">
  <div class="row">
  <div class="page-header"></div>
  <%= notice %>
  <%= alert %>

      <div class="col-md-8">
        <h3>We would love to hear from you!</h3>
      <%= form_tag(contact_index_url) do %>
        <div class="form-group">
          <%= label_tag(:contact_first_name, "First Name") %>
          <%= text_field_tag(:contact_first_name, nil, {:class => "form-control"}) %>
        </div>
        <div class="form-group">
         <!-- <label for="contact_last_name">Last Name</label>
          <input type="text" class="form-control" style="max-width:350px" id="contact_last_name"> -->
          <%= label_tag(:contact_last_name, "Last Name") %>
          <%= text_field_tag(:contact_last_name, nil, {:class => "form-control"}) %>
         </div>
          <div class="form-group">
             <!-- <label for="contact_email">Email</label>
            <input type="email" class="form-control" style="max-width:350px" id="contact_email"> -->
            <%= label_tag(:contact_email, "Email") %>
            <%= email_field_tag(:contact_email, nil, {:class => "form-control"}) %>
           </div>
          <div class="form-group">
            <%= label_tag(:advertising_title, "How did you hear about us?") %>
            <%= select_tag(:advertising_options, options_for_select([['None', 'None'], ['Advertisements', 'Advertisements'], ['At an event', 'At an Event'], ['Community Service Center', 'Community Service Center'], ['From someone else', 'From Someone Else'], ['Internet search', 'Internet Search'], ['Social Media', 'Social Media'], ['Other', 'Other']]), {:class => "form-control"}) %>
           </div>

           <div class="form-group">
            <%= label_tag(:request, "What is your request related to?") %>
            <%= select_tag(:request, options_for_select([['Press', 'Press'], ['Grants/Investment ', 'Grants/Investment '], ['Feedback About the Site', 'Feedback About the Site'], ['A Bug or Problem you Had', 'A Bug or Problem you Had'], ['Something Else', 'Something Else']]), {:class => "form-control"}) %>
           </div>

          <div class="form-group">
            <%= label_tag(:feedback, "Your message") %>
            <%= text_area_tag(:feedback, nil, {:class => "form-control", :rows => "5"}) %>
           </div>

          <div>
            <%= submit_tag("Submit", :class => "btn btn-primary") %>
           </div>
      <% end %>
      </div>
    </div>
    <div>
      <h3>Some ways to get in touch with us</h3>
    </div>

    <div>
      <ul>
        <li><a href ="mailto:mrelief.form@gmail.com">Email</a></li>
        <li><a href ="https://twitter.com/mrelief_form">Twitter</a></li>
        <li><a href ="https://www.facebook.com/mRelief">Facebook</a></li>
        <li><a href ="https://www.youtube.com/channel/UCGHiRX8a6plpA799PJILkbw">YouTube</a></li>
      </ul>
     </div>

  </div>

  </div>